### ISSUE TITLE
Null Reference Exception when using Demote API on 2.7

### ISSUE THREAD

**Issue by newatlanta19006** [heroiclabs/nakama-dotnet#46]
Hi!

I recently upgraded from Nakama 2.4 to latest (2.7) to use the new Demote Api for groups. I receive an nullreferenceexception when using the new API though. I haven't successfully executed demote yet. Before I was just using Kick then add new member for demoting before which did work but the new api is much cleaner. This is being done via a server to server call (from my .Net server to Nakama). Here is a snippet of the code I am using (exact same code works for promote api so I don't think it is a coding mistake):

```
var client = new Client(_settings.Scheme, _settings.ConnectionString, _settings.Port, _settings.Key);
client.Logger = new NakamaLogger(_logger);

var session = await client.AuthenticateCustomAsync(officer.Id, null, false);
await client.DemoteGroupUsersAsync(session, officer.AllianceInfo.AllianceId, new List<string> { memberToDemote.Id }); <--nullref
```

Here is the error:

fail: RBM_Server.Middleware.ExceptionHandler[0]
      ServerError: System.NullReferenceException: Object reference not set to an instance of an object.
         at Nakama.HttpRequestAdapter.SendAsync(String method, Uri uri, IDictionary`2 headers, Byte[] body, Int32 timeout)
         at Nakama.ApiClient.DemoteGroupUsersAsync(String bearerToken, String groupId, IEnumerable`1 userIds)
         at RBM_Server.Modules.AllianceModule.DemoteAllianceMember(Ref`1 officerRef, Ref`1 memberToDemoteRef) in d:\PizzaClub\RBM\Server\RBM_Server\RBM_Server\Modules\AllianceModule.cs:line 740
         at RBM_Server.Controllers.AllianceController.ManageAllianceRole(ManageAllianceRoleRequest request) in d:\PizzaClub\RBM\Server\RBM_Server\RBM_Server\Controllers\AllianceController.cs:line 325
         at lambda_method(Closure , Object )
         at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Anemonis.AspNetCore.RequestDecompression.RequestDecompressionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at RBM_Server.Middleware.ExceptionHandler.Invoke(HttpContext httpContext) in d:\PizzaClub\RBM\Server\RBM_Server\RBM_Server\Middleware\ExceptionHandler.cs:line 26

Version Nakama: 2.7.0+d5e0b5bb
Version .NET Nakama API: 2.7.0

Any help would be appreciated. In the meantime, I will revert back to original.

**Comment by lugehorsam** [comment]
Thanks for the report @newatlanta19006 - we'll be taking a look this week. Are you able to tell whether or not the server is receiving and responding to the demotion request? I usually do this via a `docker logs <container_id> --follow` on my local Nakama instance.

**Comment by lugehorsam** [comment]
Also note that we test the demotion API here: https://github.com/heroiclabs/nakama-dotnet/blob/master/tests/Nakama.Tests/GroupTest.cs#L193

Let me know if you're able to spot any obvious differences between your code and that test case. Looking at your snippet, I don't see anything, but I may be missing a larger picture of your code.

**Comment by newatlanta19006** [comment]
I took a look at the Nakama server logs and it doesn't seem like the demote call is reaching Nakama. So I assume the error is occurring before it executes a network call.

**Comment by newatlanta19006** [comment]
Any updates on this issue? I would like to use the Demote Api on our server but it doesn't seem to work.

**Comment by lugehorsam** [comment]
@newatlanta19006 when you run the client with a breakpoint are you able to tell what's null?

**Comment by newatlanta19006** [comment]
No, it is happening internal to the Nakama library, not in the calling code.

**Comment by lugehorsam** [comment]
@newatlanta19006 I recommend building the library from source with debug symbols and/or logs in order to see what your issue is. I don't see anything wrong with your code but like I said earlier, there is likely something in your environment or codebase that could be causing the problem.

If you have a minimal viable reproduction that would also be welcome.

**Comment by newatlanta19006** [comment]
This is where the null reference is happening after building the project and debugging @lugehorsam 
![Capture](https://user-images.githubusercontent.com/721127/107090936-cc581c00-67b5-11eb-955b-1df1d960b111.JPG)

I can confirm that Nakama (server is running on 2.7.0+d5e0b5bb. So perhaps the demote url is wrong? Not sure what else to test. Either way, it feels like the "Not Found" result should be properly handled by Nakama and thrown as a proper exception. 

As for the actual issue, please advise, I dont see anything wrong with my code or server setup. Thanks!

**Comment by newatlanta19006** [comment]
If I drill down to the url level:
Promote is available as expected:
https://nakamadev.pizzaclubgames.com/v2/group/0cc592dc-a366-4581-8692-157834de2e6f/promote?user_ids=9ff530c5-f2a4-49d4-a916-e3a9ac72fbcb&
Demote is Not Found:
https://nakamadev.pizzaclubgames.com/v2/group/0cc592dc-a366-4581-8692-157834de2e6f/demote?user_ids=9ff530c5-f2a4-49d4-a916-e3a9ac72fbcb&

I can again confirm that the server is on version 2.7.0+d5e0b5bb. So something is up with the server upgrade not properly setting up demote api. Any advice?

**Comment by lugehorsam** [comment]
Hey @newatlanta19006 the demote API was added in Nakama 2.13. Can you upgrade to that and try it?

**Comment by newatlanta19006** [comment]
Sorry @lugehorsam, I am on latest nakama server. I dont wish to downgrade. I am not sure I understand the suggestion.

**Comment by lugehorsam** [comment]
The latest release of Nakama server is here: https://github.com/heroiclabs/nakama/releases/tag/v3.1.0

**Comment by newatlanta19006** [comment]
Ohhh, perhaps I am confused then about how to upgrade docker image. When I upgrade my docker image, I usually run:
sudo docker pull heroiclabs/nakama (this is how I upgraded from 2.5 -> 2.7). 

How am I supposed to upgrade to 3.1 and future releases?

**Comment by lugehorsam** [comment]
@newatlanta19006 I'd check out the Docker docs for those sorts of q's but in this case, `docker pull heroiclabs/nakama:3.1.0`

**Comment by newatlanta19006** [comment]
Ok thanks! This looks like the problem.

If I could make a suggestion, it might make sense to make the upgrade steps more clear here:  https://heroiclabs.com/docs/install-nakama-upgrade/

If you do this without also manually updating the docker-compose.yml to the new version, it won't help much it seems
