### ISSUE TITLE
Problem running tests "RPC function not found"

### ISSUE THREAD

**Issue by mattkanwisher** [heroiclabs/nakama-dotnet#88]
I setup the tests with docker here, however a 31 of the tests fail, i'm wondering if something is just not setup correctly

```
docker-compose -f ./docker-compose-postgres.yml up
dotnet test tests/Nakama.Tests/Nakama.Tests.csproj
```

test failure errors

```
--- End of stack trace from previous location ---
  Failed Nakama.Tests.Api.RpcTest.ShouldRpcRoundtrip [6 ms]
  Error Message:
   Nakama.ApiResponseException : RPC function not found
  Stack Trace:
     at Nakama.RetryInvoker.InvokeWithRetry[T](Func`1 request, RetryHistory history) in C:\Users\hyper\source\repos\nakama-dotnet\src\Nakama\RetryInvoker.cs:line 65
   at Nakama.Client.RpcAsync(ISession session, String id, String payload, RetryConfiguration retryConfiguration, CancellationToken canceller) in C:\Users\hyper\source\repos\nakama-dotnet\src\Nakama\Client.cs:line 842
   at Nakama.Tests.Api.RpcTest.ShouldRpcRoundtrip() in C:\Users\hyper\source\repos\nakama-dotnet\tests\Nakama.Tests\RpcTest.cs:line 43
--- End of stack trace from previous location ---
```

**Comment by mofirouz** [comment]
Hi @mattkanwisher - thanks for your contribution (and your PR #89).

The test rely on runtime code be loaded by your local Nakama instance - you can find the necessary runtime code here: 
https://github.com/heroiclabs/nakama/tree/master/data/modules

Grab a copy of that, put it somewhere, point Nakama to it, and run the tests and they should pass. Thanks!
